import { BadRequestException,Injectable,NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Program,ProgramImageKind,ProgramStatus } from './program.entity';
import { CreateProgramDto,ProgramsQueryDto } from './programs.dto';
type UploadedFile={buffer:Buffer;originalname:string;mimetype:string;size:number};
@Injectable()
export class ProgramsService{
  constructor(@InjectRepository(Program)private readonly programs:Repository<Program>){}
  async findAll(query:ProgramsQueryDto){const b=this.programs.createQueryBuilder('program').orderBy('program.departureDate','ASC').addOrderBy('program.createdAt','DESC').skip((query.page-1)*query.limit).take(query.limit);if(query.search?.trim())b.andWhere('(program.name ILIKE :search OR program.season ILIKE :search OR program.ministryPermitNumber ILIKE :search)',{search:`%${query.search.trim()}%`});if(query.type)b.andWhere('program.type=:type',{type:query.type});if(query.status)b.andWhere('program.status=:status',{status:query.status});const[data,total]=await b.getManyAndCount();return{data,meta:{page:query.page,limit:query.limit,total}};}
  async findOne(id:string){const item=await this.programs.findOneBy({id});if(!item)throw new NotFoundException('Program not found');return item;}
  async create(dto:CreateProgramDto,files:Record<string,UploadedFile[]|undefined>){if(dto.returnDate<dto.departureDate)throw new BadRequestException('Return date must not precede departure date');const cover=this.requiredImage(files['cover']?.[0],'Cover');const social=files['social']?.[0];if(social)this.validateImage(social);const money=(value?:number)=>value===undefined?null:value.toFixed(2);const item=this.programs.create({...dto,status:dto.status??ProgramStatus.DRAFT,ministryPermitNumber:dto.ministryPermitNumber?.trim()||null,makkahHotel:dto.makkahHotel?.trim()||null,makkahHotelRating:dto.makkahHotelRating??null,makkahNights:dto.makkahNights??null,madinahHotel:dto.madinahHotel?.trim()||null,madinahHotelRating:dto.madinahHotelRating??null,madinahNights:dto.madinahNights??null,airline:dto.airline?.trim()||null,flightNumber:dto.flightNumber?.trim()||null,singlePrice:money(dto.singlePrice),doublePrice:money(dto.doublePrice),triplePrice:money(dto.triplePrice),quadruplePrice:money(dto.quadruplePrice),seatCashCost:money(dto.seatCashCost),description:dto.description?.trim()||null,seoTitle:dto.seoTitle?.trim()||null,metaDescription:dto.metaDescription?.trim()||null,canonicalUrl:dto.canonicalUrl?.trim()||null,coverImageName:cover.originalname.slice(0,120),coverImageMime:cover.mimetype,coverImageData:cover.buffer,socialImageName:social?.originalname.slice(0,120)??null,socialImageMime:social?.mimetype??null,socialImageData:social?.buffer??null});return this.programs.save(item);}
  async remove(id:string){const item=await this.findOne(id);await this.programs.remove(item);return{deleted:true};}
  async image(id:string,kind:ProgramImageKind){const prefix=kind==='cover'?'coverImage':'socialImage';const row=await this.programs.createQueryBuilder('program').addSelect(`program.${prefix}Data`).where('program.id=:id',{id}).getOne();if(!row)throw new NotFoundException('Program not found');const data=row[`${prefix}Data` as keyof Program] as Buffer|null;const mime=row[`${prefix}Mime` as keyof Program] as string|null;const name=row[`${prefix}Name` as keyof Program] as string|null;if(!data||!mime)throw new NotFoundException('Program image not found');return{data,mime,name:name??'program-image'};}
  private requiredImage(file:UploadedFile|undefined,label:string){if(!file)throw new BadRequestException(`${label} image is required`);this.validateImage(file);return file;}
  private validateImage(file:UploadedFile){if(!['image/jpeg','image/png','image/webp'].includes(file.mimetype))throw new BadRequestException('Only JPG, PNG and WebP images are allowed');if(file.size>5*1024*1024)throw new BadRequestException('Image must not exceed 5 MB');}
}
